# Generated by Django 5.2.17 on 2026-09-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_verify_superuser_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Успешный вход"),
                            ("login_failed", "Неудачный вход"),
                            ("logout", "Выход"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authentication_events",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="accounts_au_event_t_e4612c_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_au_user_id_93a2fd_idx",
                    ),
                ],
            },
        ),
    ]
